### PR TITLE
Fixing unneeded return linting errors

### LINKED ISSUE #5: Format codebase using Clippy
Here are two current linting issues that we can fix up:

```rust
Checking supernova v0.1.0 (/Users/sean/projects/supernova)
warning: unneeded return statement
  --> src/lib.rs:99:9
   |
99 |         return Ok(());
   |         ^^^^^^^^^^^^^^ help: remove `return` as shown: `Ok(())`
   |
   = note: #[warn(clippy::needless_return)] on by default
   = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.212/index.html#needless_return

warning: unneeded return statement
   --> src/lib.rs:137:5
    |
137 | /     return match link_headers {
138 | |         None => None,
139 | |         Some(links) => links
140 | |             .values()
...   |
148 | |             .and_then(|link_value| Some(link_value.link().to_owned())),
149 | |     };
    | |______^
    |
    = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.212/index.html#needless_return
help: remove `return` as shown
    |
137 |     match link_headers {
138 |         None => None,
139 |         Some(links) => links
140 |             .values()
141 |             .iter()
142 |             .find(|&val| {
  ...

    Finished dev [unoptimized + debuginfo] target(s) in 46.40s
```

### PR DESCRIPTION
**Pull request by Mordax**
Closes #5 . Should remove the annoying failed build badge.

### CODE REVIEW

**Comment by SeanPrashad** [comment]
Great stuff @Mordax! Travis _should_ pass with a green checkmark but it looks like there's some other things breaking the build. Check them out [here](https://travis-ci.org/0xazure/supernova/jobs/453051037#L642)!

**Comment by 0xazure** [comment]
Okay, this is interesting. The `clippy` lint in question is [`new_ret_no_self`](https://rust-lang-nursery.github.io/rust-clippy/current/index.html#new_ret_no_self), which _should_ have failed on `stable` as well.

I unfortunately can't dive any deeper on this right now because of rust-lang/rust#55817 so I can't actually install the `beta` channel to test this locally.

**Comment by 0xazure** [comment]
I'm not actually too fussed about the `beta` failure because I remove the offending method in #19, but I'd still like to figure out why the two channels are seemingly running different lints against the codebase.

**Comment by SeanPrashad** [comment]
Luckily we have our friends over at #rust:

irc_1
irc_2
irc_3

**Comment by 0xazure** [comment]
> clippy on beta is a newer clippy than the clippy on stable

I wish it were that simple. It looks like the `new_ret_no_self` lint is relatively new (within the last 30-35 days) and experienced a bunch of false positives with the initial implementation. As far as I can tell, `stable` doesn't include this lint at all, `beta` has the version with false positives, and `nightly` has the updated version that eliminates a lot of the false positives seen on `beta`, which explains why we're only seeing failures on `beta`.

**Comment by Mordax** [comment]
Clearly what's next is a billion dollar app 😎

**Pull request merged**
